quarkus:
  http:
    port: 8082
  datasource:
    db-kind: oracle
    username: magnum
    password: magnum123
    jdbc:
      url: jdbc:oracle:thin:@oracle-db:1521/XEPDB1
  hibernate-orm:
    database:
      generation: update
